permissions = {
    "Admin": [
        "read_client",
        "create_client",
        "update_client",
        "delete_client",
        "read_collab",
        "create_collab",
        "update_collab",
        "delete_collab",
        "read_contract",
        "create_contract",
        "update_contract",
        "delete_contract",
        "read_event",
        "create_event",
        "update_event",
        "delete_event",
    ],
    "Sales": [
        "read_client",
        "create_client",
        "update_client",
        "delete_client",
        # "read_collab",
        # "create_collab",
        # "update_collab",
        # "delete_collab",
        # "read_contract",
        # "create_contract",
        # "update_contract",
        # "delete_contract",
        # "read_event",
        # "create_event",
        # "update_event",
        # "delete_event",
    ],
    "Support": [
        "read_client",
        "create_client",
        "update_client",
        "delete_client",
        "read_collab",
        "create_collab",
        "update_collab",
        "delete_collab",
        "read_contract",
        "create_contract",
        "update_contract",
        "delete_contract",
        "read_event",
        "create_event",
        "update_event",
        "delete_event",
    ]
}